# Generated by Django 4.2.4 on 2023-09-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images_nase64',
            new_name='images_base64',
        ),
    ]
