# Generated by Django 4.2.4 on 2023-09-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_images_nase64_gallery_images_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='user_id',
        ),
    ]
