# Generated by Django 4.2.4 on 2023-09-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_gallery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='user',
        ),
    ]
