# Generated by Django 4.2.4 on 2023-09-05 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_gallery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.CharField(blank=True, max_length=1000000, null=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=1000000, null=True)),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status_pending', models.BooleanField(default=True)),
                ('status_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
