# Generated by Django 4.2.4 on 2023-09-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_checkin_customuser_points_galeriacheckin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeriacheckin',
            old_name='chackin',
            new_name='checkin',
        ),
    ]
